name: Deploy snapshot to github packages 

# Run workflow when the workflow to check the quality is completed
on:
  push:
    branches: [ master ]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Publish package
        run: mvn --batch-mode deploy -e -X
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
