name: Deploy release to sonatype 

# Run workflow when the workflow to check the quality is completed
on:
  workflow_run:
    workflows: [CodeQL]
    types:
      - completed
    branches: 
      - 'release/**'

jobs:
  printJob:    
    name: Print event
    runs-on: ubuntu-latest
    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        echo "$GITHUB_CONTEXT"

  release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.workflow_run.head_branch }}
        
      - name: Install Java and Maven
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Release Maven package
        uses: samuelmeuli/action-maven-publish@v1
        with:
          gpg_private_key: ${{ secrets.gpg_private_key }}
          gpg_passphrase: ${{ secrets.gpg_passphrase }}
          nexus_username: ${{ secrets.nexus_username }}
          nexus_password: ${{ secrets.nexus_password }}
          maven_goals_phases: clean deploy -DaltDeploymentRepository=ossrh::default::https://s01.oss.sonatype.org/service/local/staging/deploy/maven2
  tag:         
    runs-on: ubuntu-latest
    needs: [release]
    steps:
      - name: Checkout files
        uses: Bhacaz/checkout-files@v2
        with:
         files: pom.xml
         branch: ${{ github.event.workflow_run.head_branch }}
      - name: Get version from pom.xml
        id: get-version
        uses: JActions/maven-version@v1.2.0
      - name: Create Tag
        uses: negz/create-tag@v1
        with:
          version: ${{ steps.get-version.outputs.version }}
          message: Release version for ${{ steps.get-version.outputs.version }}
          token: ${{ secrets.GITHUB_TOKEN }}
        
        
